# Generated by Django 4.1.6 on 2023-02-08 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_ingredient_recette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='recette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.recette'),
        ),
    ]
