# Generated by Django 4.1.6 on 2023-02-08 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_ingredient_recette'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membre',
            old_name='mot_de_passe',
            new_name='mdp',
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='recette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.recette'),
        ),
    ]
